### ISSUE TITLE
Feature Request: Make a highlight of the same amounts

### ISSUE THREAD

**Issue by wvxwxvw** [namazso/OpenHashTab#10]
Make a highlight of the same amounts

**Comment by namazso** [comment]
could you specify this a bit more?

**Comment by wvxwxvw** [comment]
When you select multiple files, if the same hash occurs, then the matches will be highlighted in the list in the same color. Preferably different, or two alternating for different groups of matches.

In HashMyFiles or HashSum see the examples.

And still would make a button to sort results by matches. This is of course, if sorting by column headings is impossible. And if possible, then just add a column of “matches” so that could sort by its heading.

I don't write very well in English, I hope you understand.

**Comment by namazso** [comment]
> When you select multiple files, if the same hash occurs, then the matches will be highlighted in the list in the same color. Preferably different, or two alternating for different groups of matches.

I'll think about this. Colors are already used for sumfile match / mismatch. However, what you described kinda sounds like a file duplicate finder? Could you give me an use-case so I can figure out some UI optimized for it?

> And still would make a button to sort results by matches. This is of course, if sorting by column headings is impossible. And if possible, then just add a column of “matches” so that could sort by its heading.

Column header clicks do send a notification, so doing arbitrary action on them should be possible. What is more of a problem is that the current UI flattens two dimensional data (file x algorithm) into a single dimension list, which makes things a bit more complicated: for example errors and mismatches are for a file, but matches are for a specific hash. I'd like to improve it, but obviously moving hashes into a per-algorithm column would be awful for usage, even though it'd solve the dimensional problems.

> I don't write very well in English, I hope you understand.

It's completely understandable

**Comment by wvxwxvw** [comment]
> I'll think about this. Colors are already used for sumfile match / mismatch. However, what you described kinda sounds like a file duplicate finder? Could you give me an use-case so I can figure out some UI optimized for it?

For example, if there are different versions of text files in the same folder, you can see if there are duplicates among them. Otherwise, the meaning is lost if you still have to keep another hash calculator in the context menu.

And at least one more thing is additionally needed, either sorting by hash or highlighting the same ones. Or better yet, both.

**Comment by Riajyuu** [comment]
>Colors are already used for sumfile match / mismatch.

Why not use it for single file as well? It would be much more straightforward compared to text only.

![image](https://user-images.githubusercontent.com/16912240/77272038-1de3df00-6ca8-11ea-9a62-644a091654bb.png)

**Comment by namazso** [comment]
@Riajyuu what would happen if a sumfile for the single file was detected and applied? They could be red or green already. would the new color override it?

**Comment by Riajyuu** [comment]
> They could be red or green already. would the new color override it?

3 answer: 
1. use whatever match one from the later coming and tell the source: clipboard or file
2. highlight both and tell both sources
3. use only user action and ignore the other

Or maybe you have better idea?

**Comment by namazso** [comment]
@Riajyuu i was thinking about turning the hash list into a tree list view, like this:
![image](https://user-images.githubusercontent.com/8676443/77274491-55598800-6cb6-11ea-9544-de0908121136.png)
colors are not implemented in this short test program, I was only trying out a library, But this would let me color the whole line of the files to green/red with possibly a button to close all if you only care about the files match / mismatch state

**Comment by wvxwxvw** [comment]
It seems like a good idea.

**Comment by rbnmndz** [comment]
At least, it would be more clear if a ✔️ (tick)￼ or "match" was added to the result below, next to the algorithm or file name, and in the list of hashes meanwhile it is not highlighted with other colour.

**Comment by megosugit** [comment]
> > Colors are already used for sumfile match / mismatch.
> 
> Why not use it for single file as well? It would be much more straightforward compared to text only.
> 
> ![image](https://user-images.githubusercontent.com/16912240/77272038-1de3df00-6ca8-11ea-9a62-644a091654bb.png)

Yes, please highlight the matching line when checked against 👍😍

**Comment by vertigo220** [comment]
Agree with @megosugit about highlighting hashes that match with the "Check against" box contents. I assumed that's what was supposed to happen and thought maybe there was a bug when I wasn't seeing any. As for concern regarding clashing with sumfiles, a basic match could use a border and a sumfile match could use a highlight, or a basic match could be bolded/italicized/etc. There are also multiple issues related to this (#23 and #131 at least). It looks like dealing with this is already planned for v4, but just wanted to share my thoughts on it as well.
