### ISSUE TITLE
Hashes aren't being checked against clipboard contents

### ISSUE THREAD

**Issue by krwudtke** [namazso/OpenHashTab#101]
I just discovered, downloaded and installed your software. So far it seems to be working correctly except this one thing.
As you can see in the screen shot below, there is a number in the "**Check against:**" box, but it doesn't seem to be checking it. 
The numbers next to **Done!**, in this case, (0/0/1/0), would seem to indicate that it isn't finding the number in the box as something to check against.
I tried changing some settings (unchecked **MD5**, unchecked "**Only if no algorithms of that length are enabled**") and MD5 was still shown, as well as MD4 and XXH3-128. So it is finding the correct length, it just isn't doing the check.
Is this a bug, or am I missing something?
Thanks, Kevin

![image](https://user-images.githubusercontent.com/7281718/152250632-103cf3b5-8094-4b95-afc4-8ff066c6d244.png)

**Comment by namazso** [comment]
It does check, it writes right below the text box which one it matched up with. Working as intended

**Comment by krwudtke** [comment]
OK, I see it now. I thought that was just saying what file name that had
been hashed. I was expecting some green shading on the MD5 hash and the
numbers to be (1/0/0/0) as in the screen shot in the Readme.md file.
Thanks for the clarification.
Kevin

**Comment by namazso** [comment]
Glad it's solved.

The numbers are for ones matched up with hashes found in files. So if you had a file named `Avidemux_2.8.0VC++64bits.exe.md5` it'd find that, read the hash, match it up, and show `(1/0/0/0)` (or `(0/1/0/0)` if it doesn't match)

**Comment by krwudtke** [comment]
Cool, thanks!
