### ISSUE TITLE
Clearer product name in UI

### ISSUE THREAD

**Issue by yfdyh000** [namazso/OpenHashTab#104]
The product name is missing in the current UI, so it may be difficult for the user to understand which software provides the functionality.

* I'm not sure how to open [this UI](https://github.com/namazso/OpenHashTab/blob/master/resources/screenshot.png).
* [The window title](https://github.com/namazso/OpenHashTab/blob/master/resources/algorithms.png) is just the `*`, I'm not sure what it means, and why not the "OpenHashTab". 
* No project page link in options interface.
* The tab label is localized in the Properties window, like the "Hash 校验" (I'm not sure where it's located in the code).

**Comment by namazso** [comment]
This is intentional (for the tab version) as it's meant to look like a part of the OS. I really should add some branding to the settings though.

> I'm not sure how to open this UI.

Open from context menu if you enabled that option when installing, or open via file association if you have those enabled.
