### ISSUE TITLE
Make colors configurable

### ISSUE THREAD

**Issue by xmha97** [namazso/OpenHashTab#106]
Please change colors like the HashCheck app
![image](https://user-images.githubusercontent.com/23485114/158365807-74ecc38b-6310-4cd2-becc-c4fea27b6a63.png)

**Comment by megosugit** [comment]
yes, please :)

**Comment by g0blin-NN** [comment]
I already asked. they said it was made on purpose....
https://github.com/namazso/OpenHashTab/issues/81#issuecomment-861585401

**Comment by namazso** [comment]
I kept this open to remind me that I still want to make the colors configurable (even if the default colors do make sense) @g0blin-NN
