### ISSUE TITLE
Virustotal disable

### ISSUE THREAD

**Issue by xolox2k** [namazso/OpenHashTab#109]
Please add an option to disable virustotal at install. Without that this app isn't fully offline.

**Comment by namazso** [comment]
.. it is disabled. You must click the VT button, then click yes on the license terms first to do any connections to VT. If you can accidentally click two different buttons somehow, how would 3 change anything?

**Comment by xolox2k** [comment]
Yeah but anyone in organisation can click enable. And after that it's hard to disable.

**Comment by xolox2k** [comment]
It's very easy to enable (even accidentally) but no way to permament disable. Many organisation can't send any data outside European Union.

**Comment by namazso** [comment]
Yea I get it, the end user might not be the smartest in an organization, so Admin has to disable. I could add a global disabling registry key, but that wouldn't be part of the installer, as I think it should work even when it's an "user" install.

Would that be fine?

**Comment by xolox2k** [comment]
That should be enough !

**Comment by namazso** [comment]
Available in latest development builds: create a value named `ForceDisableVT` in `HKLM\Software\OpenHashTab` and set it to a non-zero value. Doing so will disable the button:

![image](https://user-images.githubusercontent.com/8676443/163732798-79cb8950-1fa8-4ca4-a874-87f8a1b3177e.png)
