### ISSUE TITLE
Shall we have new release ? 

### ISSUE THREAD

**Issue by Remonli** [namazso/OpenHashTab#110]
Hi , 

It has been more than one year since last release, is it right time for a new release ? 

Thank you.

**Comment by namazso** [comment]
I tagged the issues I intend to fix before a new release with a milestone: https://github.com/namazso/OpenHashTab/milestone/2

**Comment by KirkH420** [comment]
Remonli, you could always compile a copy for yourself. There have been updates, they just haven't been turned into releases.

**Comment by namazso** [comment]
no need to compile yourself, CI publishes autobuilt artifacts

**Comment by namazso** [comment]
This was solved: https://github.com/namazso/OpenHashTab/releases/tag/v3.0.2
