### ISSUE TITLE
Windows Server support

### ISSUE THREAD

**Issue by giumas** [namazso/OpenHashTab#114]
Any hope of having OpenHashTab running on Windows Server? 
Is it already possible? If not, what is stopping from supporting Windows Server?

**Comment by namazso** [comment]
I think it should already work just fine, but I'll check

**Comment by oveand** [comment]
Tried installing user-edition on Windows Server 2012 R2 and Windows Server 2016 and no context menu integration appears after installation. Also tried logging out/in again to restart Explorer.

Perhaps some limitations on server configuration?

**Comment by namazso** [comment]
Possibly, maybe it only allows signed extensions, or maybe none at all. Server does have some stricter policies by default around these things.

**Comment by giumas** [comment]
How can we figure what is the blocking issue here?

**Comment by namazso** [comment]
I'm looking into it right now, didn't have a Server VM ready as I only keep around one of each consumer editions normally.

**Comment by namazso** [comment]
I can't reproduce this issue. Just tried out on a fresh install of *Windows Server 2022 Datacenter (Desktop Experience)* and these all work just fine:

* v3.0.1 user
* v3.0.1 system
* v3.0.1-146-gaca0e2c user
* v3.0.1-146-gaca0e2c system

![image](https://user-images.githubusercontent.com/8676443/165720756-3483a5c6-673c-4a1f-ba48-476fe9b8e67c.png)

I'd still recommend trying the system install too on whatever setup you have, as that one adds itself to the list of approved shell extensions

**Comment by oveand** [comment]
Great, I can confirm that system install works on Windows Server 2016 too while on our servers user install doesn't.

Currently I'm not allowed to do system installation on 2012 but this is most likely the issue.
Thank you for investigating!

**Comment by giumas** [comment]
Many thanks for your rapid reaction to this ticket!
