### ISSUE TITLE
Hashing a folder crashes explorer

### ISSUE THREAD

**Issue by Xanderplayz16** [namazso/OpenHashTab#118]
OS: windows 11
Hardware: Dell inspiron 3080

**Comment by namazso** [comment]
Does it reproduce on the latest development build? 
If so, would you mind generating and sending me (preferably in email as it may contain private data) a memory dump? Enabling automatic generation of them is described here: https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps if you need help with it just comment.

**Comment by demberto** [comment]
@namazso Yes can confirm it for Win 10 as well. This is caused for special shell folders only like Documents, Downloads, etc. Easiest solution would be to blacklist those paths.

**Comment by namazso** [comment]
I can't reproduce this. Just tried it on every folder in my user folder with 3.0.2 and besides the long wait (due to some 790k files) it went through just fine. If your problem is just performance of initial enumeration, then it's a dupilcate: #116
