### ISSUE TITLE
Chinese Installer Texts Garbled

### ISSUE THREAD

**Issue by Riajyuu** [namazso/OpenHashTab#120]
![image](https://user-images.githubusercontent.com/16912240/173004298-09ced0d1-a825-4b17-841d-52293b797f0d.png)
![image](https://user-images.githubusercontent.com/16912240/173004364-795a134b-1e1c-4942-9f3e-f109ddb0937c.png)
These are final two steps before actual installation process.

**Comment by namazso** [comment]
huh, apparently innosetup needs a BOM to have it accept a file as UTF-8: https://stackoverflow.com/a/51066427
