### ISSUE TITLE
VirusTotal false positive (1/66)

### ISSUE THREAD

**Issue by MadZiontist** [namazso/OpenHashTab#122]
MS Edge warns me to be careful about it when I try to download it, and I have to go through a couple prompts, and choose to keep the file for it to save. 

Also it's flagged in VirusTotal:

Vendor:
Cynet

Malicious (score: 100)
Acronis (Static ML)

Undetected

I'm going to hold off on re-installing it. When I did have it installed previously it wasn't showing up in menu as a Windows shell extension, for another thing.

I hope this is worked out, because I really like the app, and was looking forward to the update.

**Comment by namazso** [comment]
> MS Edge warns me to be careful about it when I try to download it, and I have to go through a couple prompts, and choose to keep the file for it to save.

that is normal. As more people download it will go away

> Also it's flagged in VirusTotal:

1 flags is practically nothing. the previous update started off with 5. As usual, it will decrease as time goes. I contacted them by mail a few days ago too.

>  When I did have it installed previously it wasn't showing up in menu as a Windows shell extension, for another thing.

I am not sure what you mean. The context menu feature? That's provided as an option in the installer, you can toggle it

**Comment by namazso** [comment]
Oh, also, if you're overworried about that random AV vendor, feel free to compile the code yourself. It's configured to be completely reproducible, so as long as you have the same version tools as the GitHub runner which built it, your builds should match exactly by hash.

**Comment by MadZiontist** [comment]
Ok, I re-installed it and it was in the context menu this time. I don't remember toggling the option off previously. But maybe it was some sort of user error. 

I do use Windows Defender, along with DefenderUI (an interface for it with better management of the settings). But I also scan my .exe's with VirusTotal (for extra measure). You're right, it was only one result (and from an obscure vendor). I'm not too concerned about it. I don't yet know how to compile from source, btw.

**Comment by namazso** [comment]
Cynet (AV vendor) unresponsive to mails (I mailed soc@cynet.com on 2022-06-10 05:31), so closing this, there is nothing I can do.

**Comment by namazso** [comment]
Update: after 16 days they managed to answer and remove the detection
