### ISSUE TITLE
Windows 10/11 Deployment -> Hangs

### ISSUE THREAD

**Issue by LuxLOL** [namazso/OpenHashTab#123]
Hi,
I have a big problem with the last version (3.0.2) with my Windows 10/11 Deployment.
When I use the "SetupComplete.cmd" file to install the OpenHashTab during the Windows 10/11 installation then the whole Windows 10/11 installation will hang on the "Just a moment" screen.

I thing the problem happens because Windows 10/11 is not running under a normal User Profile account.

I cannot post an error message because Windows is hiding this things during the Windows 10/11 installation.
But when using the old version "OpenHashTab v3.0.1 **Setup User** or **Setup System** then everything works fine.

**Comment by namazso** [comment]
try adding the /CURRENTUSER or /ALLUSERS flag to the installer

**Comment by LuxLOL** [comment]
The flag "/ALLUSERS" worked for me. 😃
The flag "/CURRENTUSER" did not bock the Windows 10/11 installation but OpenHashTab was not installed.
The flag "/ALLUSERS" also blocked the Windows 10/11 installation.

Glad the problem could be solved with one command. 👍
Thanks!

**Comment by namazso** [comment]
> The flag "/CURRENTUSER" did not bock the Windows 10/11 installation but OpenHashTab was not installed.

yeah, since then i realized this would install it to the temporary account that is deleted after you get through OOBE. So it's technically installed, just got deleted together with the account a few minutes later.
