### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by lp1017** [namazso/OpenHashTab#128]
When there are more than 198 hexadecimal numbers [0-9a-f] in the clipboard, opening hashtab will crash

**Comment by lp1017** [comment]
![2022-07-01 021847](https://user-images.githubusercontent.com/13939211/176751144-5dc94a28-735b-4781-9170-a6d21d686197.jpg)
Crash caused by too long data in the text box

**Comment by namazso** [comment]
same cause, regex in Microsoft's STL is just bugged. Seems like I'll have to switch to a library instead
