### ISSUE TITLE
Single hash files detected as sumfiles but aren't processed meaningfully

### ISSUE THREAD

**Issue by lp1017** [namazso/OpenHashTab#129]
hashing a file like this:
[1111.txt](https://github.com/namazso/OpenHashTab/files/9020499/1111.txt)
show blank
![2022-06-30 222135](https://user-images.githubusercontent.com/13939211/176701639-2dffe676-24d0-4cd4-a233-fdfc31b494a5.jpg)

Can't move to recycle bin
![2022-06-30 221724](https://user-images.githubusercontent.com/13939211/176701062-c527850a-ff58-4f21-9a9f-b0c71f031143.jpg)

**Comment by jpc-ae** [comment]
I've experienced this as well with windows ffmpeg as an example. When opening `ffmpeg-5.1-full_build.7z.sha256` with `ffmpeg-5.1-full_build.7z` sitting next to it, I get a similar window to the one already posted.

It seems that OpenHashTab doesn't recognize the file to campare the hash with as it's not included in the contents of the file. The sha256 file only includes the hash itself, so to process it meaningfully, the name prior to the .sha256 should be taken as the file to compare, and of course sha256 as the algorithm.
