### ISSUE TITLE
Clipboard hash check isn't clear that a file was found

### ISSUE THREAD

**Issue by redactedscribe** [namazso/OpenHashTab#131]
At least on first use being new to the program, a hash loaded from the clipboard to automatically check against isn't immediately obvious that a hash has been found. Only when I deleted a letter from the _Check against_ hash string did I realise that a there was in fact a match (because the string below changed to _No match found_).

Perhaps the "SHA-1 / Filename.ext" result under the _Check against_ field could be displayed in the Match colours when matched? Or prefix the result string with "Found: "?

Also, when a match is found, if we could click the result string and have it select and scroll to the matched hash in the list above, that could be nice, for example, to easily see any other hashes calculated for that file.

See also [this comment](https://github.com/namazso/OpenHashTab/issues/101#issuecomment-1029008177).

Thanks.

**Comment by corobin** [comment]
i came here to raise essentially the same issue.

it is not only for clipboard matches but any match with the "check against" input field.

The current ui is not super obvious whether the current file matches the hash inputted.

in comparison: hashtab puts a very large green check mark or red X mark with accompanying text to promonently  indicate whether there's a match.
