### ISSUE TITLE
Localization: German

### ISSUE THREAD

**Issue by akuropka** [namazso/OpenHashTab#14]
I didn't find any value for the tab name in german.json but instead of "Hashen" it would be better to use "Hashes" (the formal plural of "Hash" in German).

Also, "sumfile" is not commonly used in German, "Prüfsummendatei" would be the term.

**Comment by namazso** [comment]
"Hashen" is already corrected to "Hashwerte" in master. Does "Hashes" fit even better than that?
About the sumfile thing i'm not sure. It's kind of a made up word, because it's the specific format of *sum programs

**Comment by akuropka** [comment]
But the _tab name_ is still "Hashen"? "Hashwerte" would work as well, just "Hashen" sounds strange. I attached a screenshot how it looks like with me.
![20200413-101928](https://user-images.githubusercontent.com/22570574/79105527-21cbc400-7d71-11ea-8f84-c47dca202a43.png)

For me "sumfile" has no related meaning especially since the official .sum-extension is not related to checksums.  Your italian localization uses "file di checksum" which is exactly "Prüfsummendatei". In Chinese it is "Hash 文件" ("Hash file") which can be used either ("Hash-Datei") and should be generally understandable though it is to some extend made up either.

**Comment by namazso** [comment]
> But the tab name is still "Hashen"? "Hashwerte" would work as well, just "Hashen" sounds strange. I attached a screenshot how it looks like with me.

That's correct, the change has been added since the release (thats why i said it's different in master). I plan the next release to when I had time to change around the list to a listtreeview, but that needs some internal changes related to how matches work.

> For me "sumfile" has no related meaning especially since the official .sum-extension is not related to checksums. Your italian localization uses "file di checksum" which is exactly "Prüfsummendatei". In Chinese it is "Hash 文件" ("Hash file") which can be used either ("Hash-Datei") and should be generally understandable though it is to some extend made up either.

Different people did the different translations, I didn't control it too much. Anyways, I'll change that one then.

**Comment by akuropka** [comment]
I was just wondering because the latest commit (https://github.com/namazso/OpenHashTab/commit/f0ba79f8820acc85180dec0cbce21c41b0bf2670) was already in the release.

Anyways just a suggestion, thank you for considering. (-:
And thanks for your great work, nice tool, btw.

**Comment by namazso** [comment]
thanks!

Anyways, I changed the sumfile one in https://github.com/namazso/OpenHashTab/commit/980cb1316ece315f418f4aa6c898d46b6ed27fc9 , will be available in next release.

**Comment by namazso** [comment]
New release is out with this change applied.
