### ISSUE TITLE
简体中文安装界面乱码

### ISSUE THREAD

**Issue by x72171** [namazso/OpenHashTab#152]
![04153748](https://user-images.githubusercontent.com/105708677/205479779-0f9d9f4b-7c46-45e8-8084-45b3c58264ad.png)

**Comment by 250909895** [comment]
而且，检查对比界面，没有颜色显示！！

**Comment by namazso** [comment]
The setup encoding problem is known and fixed in development builds; I just haven't had time to do a release yet.

**Comment by RoachLin** [comment]
> The setup encoding problem is known and fixed in development builds; I just haven't had time to do a release yet.

Could you tell me what are these options in English? Although these options in Chinese is broken, I can still read English. Thanks!

**Comment by namazso** [comment]
Yep, it's these:

https://github.com/namazso/OpenHashTab/blob/master/installer.iss#L89-L96

**Comment by ukwangk** [comment]
非常感谢作者的辛勤开发

**Comment by microka** [comment]
我也遇到这个问题了

**Comment by namazso** [comment]
Fixed in latest release
