### ISSUE TITLE
hash entries are not highlighting

### ISSUE THREAD

**Issue by ndgit212** [namazso/OpenHashTab#155]
Expected behavior as shown in the main code page:
![image](https://user-images.githubusercontent.com/122458161/211821876-affc5045-0681-4918-ac2b-3d4553ec1b6e.png)

When i go to hash a file, it indicates the hash is valid in tiny text but is does not also highlight it to make it obvious at a glance if it is valid or not:
![image](https://user-images.githubusercontent.com/122458161/211821674-4461558b-5d10-443a-968e-1fdeea09ab94.png)

Here are my settings to confirm i have it setup properly:
![image](https://user-images.githubusercontent.com/122458161/211822214-810226f4-f647-48ff-a8c0-9ce863f607c1.png)

Does the highlighting only work when using a sumfile, or does it also work when hashing a single file and copying the sum string into the "Check Against" field?

**Comment by AndreCunha1** [comment]
I got here expecting the same, so I upvote this idea of highlighting hashes when they match what is in the "Check against" input field 👍

**Comment by namazso** [comment]
The problem is both (sumfile and the checker field) might be simultaneously used. What would you propose be the behavior in that case?

**Comment by MorpheusUK** [comment]
I also expected it to highlight when the "Check Against" field matched as it isn't clear from the GUI that it doean't apply to that field. I see the problem with the sum files so how about changing the background of the "Check Against" field itself when it matches. Thus if both a sum file and the field are used or just one both will have visible colour coding.

**Comment by namazso** [comment]
Oh, that's a great idea, there's a window message for that: https://learn.microsoft.com/en-us/windows/win32/controls/wm-ctlcoloredit
