### ISSUE TITLE
Sorting created check sums

### ISSUE THREAD

**Issue by orbittwz** [namazso/OpenHashTab#157]
Hey!
It seems this remains an issue, when a check sum is created, the order of the files is not sorted...
Can this be fixed?

**Comment by namazso** [comment]
Sorted by what?

It should be fairly possible as currently the exported file is constructed in-memory.

**Comment by orbittwz** [comment]
by filename of course...
for example...
files with prefix 01, 02, 03 etc. are not sorted, and they go 03, 08, 01, 05, 04 etc...
so files added to the check sum should be sorted by filename
thanks

**Comment by orbittwz** [comment]
possible? going to be on next release?

**Comment by orbittwz** [comment]
it's not that hard to implement, and filename is pretty straightforward here...
path is not relevant since you don't create checksum for folder but for files.

**Comment by MG240** [comment]
@namazso Could you kindly implement this?

**Comment by redactedscribe** [comment]
@namazso When reading a name sorted checksum file (did so manually using 3.0.3), it is not checked (or at least, displayed in OHT) in the order that the file specifies. I'm not sure if 173814d addresses that too.

**Comment by namazso** [comment]
@redactedscribe No, that is by design. Files are checked in parallel, and displayed in completion order. You can sort the results by clicking on the columns

**Comment by orbittwz** [comment]
Hey!
Got 3.0.3, still files in the checksum aren't sorted by file name...
Also, for HIGH DPI resolution the program is not displayed correctly.
![image](https://github.com/namazso/OpenHashTab/assets/45605734/9e3d3a21-ea1e-44d3-9bd8-ec615ec788a8)
The version in the settings menu is also not updated...
Can you check this?

**Comment by namazso** [comment]
Because that's 3.0.2 as it says. You probably already had it loaded into explorer when you tried installing over. Log out and log in. If it doesn't work, uninstall, log out, log in, install.

**Comment by namazso** [comment]
@orbittwz HiDPI works on my machine. Can you tell more about your setup?

Property sheet:

![image](https://github.com/namazso/OpenHashTab/assets/8676443/091f7e41-fc73-4736-83ef-047dd04e2475)

Standalone:

![image](https://github.com/namazso/OpenHashTab/assets/8676443/a55dacc8-a722-40af-9b9b-1b941bbbf82d)

**Comment by orbittwz** [comment]
![image](https://github.com/namazso/OpenHashTab/assets/45605734/74ed619b-2958-4444-bbb3-14f3cb612c8d)
I'm on external display, once I log out and log in, the program is displayed fine...

**Comment by orbittwz** [comment]
can confirm that created checksums are sorted by filename now!
thanks :)
