### ISSUE TITLE
Feature Request: Check Against existing verification file

### ISSUE THREAD

**Issue by zhudock** [namazso/OpenHashTab#16]
Possibly shrink the width of the existing "check against" box and add a "Open" button to browse for an existing verification file (*.md5, *.sfv, *.sha256, etc)

Or similar to [HashCheck](https://github.com/gurnec/HashCheck), an Open With capability for the verification files that includes a Pass\Fail indicator

![hashcheck_verification](https://user-images.githubusercontent.com/12414689/79337795-31274a80-7ef4-11ea-8a96-f3229da0debd.jpg)

**Comment by namazso** [comment]
Multiple variations of this feature already exists. Is there any reason this would be better? sum files can contain complete / relative paths, blindly matching them would be problematic, this is why you're expected to open it directly, rather than having an option to browse for it.
