### ISSUE TITLE
Windows Explorer restarts when opening the Hashes tab.

### ISSUE THREAD

**Issue by jngit23** [namazso/OpenHashTab#160]
Good morning.
 I'm facing a problem, OpenHashTab worked for me only at first, then it didn't want to work anymore;  Windows Explorer restarts when opening the **Hashes** tab in Properties (Alt+Enter), I looked at my clipboard and I still had a Hash copied, when copying any text I could see that the **Hashes** tab is back to work, I disabled **If in the clipboard there is any hash, automatically enable algorithms of that length for execution** trying to solve the problem to find that when using the Check Hash field the problem persists.  I'm using Windows 11 Version 22H2 (Operating System Build 22623.1325).

![explorer_oF3dtq9L3k](https://user-images.githubusercontent.com/107755720/224032706-f56fd556-f206-43d1-ac03-8ef8dbca1668.gif)
I really liked the software, grateful in advance for being able to solve it.

**Comment by KyodaiKen** [comment]
I am having the same issue. It seems to affect files over 1 GByte in size.

**Comment by jpstotz** [comment]
I also encountered the Explorer crash issue. This happens if the option `Automatically reformat pasted hashes in checker field` is active and a SHA-256 hash is located in clipboard when opening hash tab.

The file to be hashed was just about 50MB, so it can not be a memory issue.

**Comment by kurtmckee** [comment]
@jpstotz the issue you're reporting is unrelated -- it's reported in #142, and has been fixed, but the fix has not been released in a new version yet.

**Comment by namazso** [comment]
Fixed in dev builds

**Comment by kurtmckee** [comment]
@jpstotz @jngit23 dev builds can be found by going to the Actions tab above and selecting a recent successful run. At the bottom of that run page you'll find a section named "Artifacts", and you can download the `setup` artifact, which is a dev build that contains the latest code changes.

For example, this is a recent run as of today:

https://github.com/namazso/OpenHashTab/actions/runs/5562378240
