### ISSUE TITLE
The hash value type is incorrectly determined, resulting in unrecognized results。

### ISSUE THREAD

**Issue by dai640** [namazso/OpenHashTab#162]
The hash value is actually the MD5 value, but openhashTab determines it to be CRC32, so the best checksum judgment is wrong.
![hash](https://user-images.githubusercontent.com/8486208/226111332-b58e5603-3f6a-4e8b-95c4-11815cc26318.jpg)

**Comment by dai640** [comment]
I guess openhashTab is because this hash is worth the first 6 bits are numbers, so it is directly judged as CRC32.

**Comment by namazso** [comment]
Fixed in https://github.com/namazso/OpenHashTab/commit/88b52509b36f8ab3c518c05dad2bee075b418a0f
