### ISSUE TITLE
Nothing shows up in context menu? W7

### ISSUE THREAD

**Issue by ganego** [namazso/OpenHashTab#17]
- Installed v2.2.0 on W7x64.
- Right clicking any file does not show a new context menu entry for OpenHashTab.

No idea what else I should write that could be helpful :)

**Comment by namazso** [comment]
There isn't supposed to be anything in the context menu, this extension adds a property sheet as seen on the screenshots.

**Comment by ganego** [comment]
Oh, no I realize what the screenshot shows exactly. I did not expect this to be there since I have never seen any program add anything to those tabs.
