### ISSUE TITLE
vitustotal check utility giving error 

### ISSUE THREAD

**Issue by joebeem** [namazso/OpenHashTab#171]
When I tried to check a file against virus total, I used to click  the icon to upload to the site 1here it would display the number of positives found. I've done this for as long as I can remember. However, recently it has started throwing an error message when I try to check any file. attached below.

![2023-06-07](https://github.com/namazso/OpenHashTab/assets/11804592/b62e07bc-dbf8-47e9-beab-4b0b6745b38d)

Is this a known issue or isolated to me?

**Comment by namazso** [comment]
Huh. I'll see what I can do.

OpenHashTab uses the API key and endpoint from the Process Hacker (now System Informer) project. It seems like they're suffering from the same issue:

![image](https://github.com/namazso/OpenHashTab/assets/8676443/88fa9a72-db9c-4e0e-bf7d-905e7d3de721)

I'll check if the Microsoft tools using the same endpoint also have this

**Comment by namazso** [comment]
Fixed in https://github.com/namazso/OpenHashTab/commit/921305f5d4e2f001b845881e9d412a20071035c6

**Comment by joebeem** [comment]
Hi,

Sorry to bother you again, but it seems like this has come up again in a slightly different form. I thought it was the same error initially, but upon further inspection, it looks a little different. Is this something that can be looked at and possibly addressed? Thank you for taking the time to read and investigate this report.

![20230708_104609-screenshot](https://github.com/namazso/OpenHashTab/assets/11804592/602c5de1-e56c-44dd-9b26-aa251a78effa)

**Comment by namazso** [comment]
@joebeem probably a temporary issue or an issue on your end (maybe VT blocked your ip / range?), because it works just fine here on the dev builds.
