### ISSUE TITLE
Internationalization language errors

### ISSUE THREAD

**Issue by XMuli** [namazso/OpenHashTab#176]
In Win10 22H2, Simplified Chinese environment, the installer appears garbled

![image](https://github.com/namazso/OpenHashTab/assets/33887845/e4289172-de70-4670-9371-55e123025c9f)

![image](https://github.com/namazso/OpenHashTab/assets/33887845/39e33743-012f-4ca6-8db8-5b45d995b7a7)

**Comment by namazso** [comment]
Duplicate of #152, already fixed in development version
