### ISSUE TITLE
SHA-512 hash unable to match

### ISSUE THREAD

**Issue by StrangePeanut** [namazso/OpenHashTab#179]
## Steps to replicate

1. Right click any file
2. Go to Properties
3. Go to the Hashes tab
4. Right click and copy the SHA-512 hash shown
5. Paste the SHA-512 hash into the 'Check against' field
6. Result: 'no match found'

**Comment by namazso** [comment]
Huh, indeed, I think I might have messed up the math for the maximum length of a hash.. There probably shouldn't be one at all. This is unfortunate, I think I'll have to do a 3.0.4 now. Although the signing was a bit broken too anyways (some InnoSetup components weren't signed), at least I get to fix that.

**Comment by StrangePeanut** [comment]
Cheers for the prompt fix!
