### ISSUE TITLE
Version 3.0.3 does not run in Windows 32-bit - Version 3.0.2 does.

### ISSUE THREAD

**Issue by TeslaMagic** [namazso/OpenHashTab#183]
Just a heads-up...

Version 3.0.3 appears to install (mostly) in 32-bit Windows but does not finish. It says it is only for x64 and ARM64.

This is fine, but it should be noted that v3.0.3 only runs on 64-bit Windows.

Version 3.0.2 installs and runs fine in 32-bit.

**Comment by namazso** [comment]
It is noted in the changelog

**Comment by namazso** [comment]
I tested this and for me it instantly errors as intended:

![image](https://github.com/namazso/OpenHashTab/assets/8676443/93d8dd0f-cea2-4a8c-ba38-5e5a774ac784)

**Comment by namazso** [comment]
@parasiteoflife as of 3.1.0, this is not only done, but the x64 version will install both.
