### ISSUE TITLE
Hash value "Insecure"

### ISSUE THREAD

**Issue by DHFan45** [namazso/OpenHashTab#192]
Good day, can you please explain to me how the following analysis of the program is to be interpreted?

When I check a file, the result of the "hash check" is always classified as "Insecure" (color highlighted) even though the hash value matches.
Can you please explain me under which conditions a hash value is "Insecure" ? Is the file or the result still to be understood as error-free?

Under which conditions is a hash value highlighted in green and has the value "match" ?

Thank you
![Unbenannt](https://github.com/namazso/OpenHashTab/assets/123426586/d8e17cdb-8b4f-436f-b5c9-7aab0af638c2)

**Comment by namazso** [comment]
Unsafe just means that the algorithm used is not (or not any more) cryptographically secure, and you shouldn't trust it for ruling out malicious modifications.
