### ISSUE TITLE
Question about three settings and window size

### ISSUE THREAD

**Issue by Hweord** [namazso/OpenHashTab#197]
Hi, I'm using OpenHashTab for a long time. I have some problems with OHT. Firstly what is these settings for. I can't understand what they are doing.
1- Look for sumfiles next to files being hashed.
2- Strict mode for hash checker field.

Second thing is in Turkish language the number area is broken. You can see below the text.
![image](https://github.com/namazso/OpenHashTab/assets/62911598/3cee37e1-bec1-4fb2-a4d0-a3329bf75d52)

And the last thing is can we adjust the default window height and length? If we can't adjust them is a good idea.

My English is not my native language, sorry for my bad sentences. Thanks for yours help!

**Comment by namazso** [comment]
Adjusting window size is only possible in standalone mode (the one you open from context menu), and not possible in property sheets. Best would be just shortening the translation somehow, which anyone can do on Weblate

> Look for sumfiles next to files being hashed.

If you're hashing `example.txt`, OHT will try to locate `example.txt.sha256` and try to use it as sumfile.

> Strict mode for hash checker field.

The hash entry field (the text box) automatically finds hashes in the field by default, even if non-hash content is around it. Strict mode makes it only accept hashes and extra whitespace, and no other garbage.

**Comment by Hweord** [comment]
> Adjusting window size is only possible in standalone mode (the one you open from context menu), and not possible in property sheets. Best would be just shortening the translation somehow, which anyone can do on Weblate

Thanks for your other responses. Can I set a default window size for context menu? Or it's always come with default size?

**Comment by namazso** [comment]
It always comes at the default size, but saving and restoring that is actually a good idea

**Comment by Hweord** [comment]
> It always comes at the default size, but saving and restoring that is actually a good idea

Yea that's right. Thank you so much for your help.
