### ISSUE TITLE
Installer doesn't create all files on arm windows 11

### ISSUE THREAD

**Issue by headhunter45** [namazso/OpenHashTab#198]
<img width="595" alt="image" src="https://github.com/namazso/OpenHashTab/assets/672652/031353c5-5efb-4001-b202-cdac2f913cb7">
These seem to be all the files created by the 3.0.4 installer. I'm using Windows 11 Pro in Parallels on an M1 mac. Windows version 22H2 22621.2428. The installer runs and seems to complete successfully. I'm seeing some registry keys created including 2 pointing to "C:\Program Files\OpenHashTab\StandaloneStub.exe" and "C:\Program Files\OpenHashTab\OpenHashTab.dll" which don't exist. So I don't get a context menu or the sheet when I open properties.

I also tried the latest build #290 from here https://github.com/namazso/OpenHashTab/actions/runs/6764171588 with the same results.

I was able to work around this by downloading the unpacked zip from github actions and manually copying the arm64 files into "C:\Program Files\OpenHashTab" I'm not sure if I should have put them in "C:\Program Files (Arm)\OpenHashTab" which doesn't exist or not.

**Comment by dmuiX** [comment]
Thanks for this report. 
I can confirm it. No creation of an entry in Context Menu in Win11 arm Parallels on Macbook Air M1. 
Interestingly the same happens when I install hashtab, which is no longer maintained, but still works on Win11 x86.

**Comment by Archer36** [comment]
Same issue here as well. Unfortunately, the GitHub action artifacts have expired so I can't access the unpacked files any longer.

**Comment by mrutter** [comment]
Hello everybody,
I had the same issue but I was able to solve it without action artifacts.
I'm using Parallels Desktop on Mac M4 and Windows 11 ARM as guest O.S..

Using innounp.exe (https://innounp.sourceforge.net/) you can extract all the files from the installer.
Once unpacked the files, simply copy the correct version of OpenHashTab.dll to the installation folder:

- Use OpenHashTab,1.dll for x64
- Use OpenHashTab,2.dll for ARM64

Finally I disconnected from Windows and logged in again! It's working.
