### ISSUE TITLE
FP (?) WinX Defender

### ISSUE THREAD

**Issue by JohnLGalt** [namazso/OpenHashTab#2]
The newest OHT Triggers a warning on Windows 10 Defender.

![OpenHashTab](https://user-images.githubusercontent.com/7432512/74107916-cac42b80-4b42-11ea-81d6-26100def34b1.png)

**Comment by namazso** [comment]
interesting, I have Defender disabled so didn't notice.
I'll check out how I'm supposed to report false positives.
The installer didn't change at all, so must be the extension itself getting flagged

**Comment by namazso** [comment]
From a quick VirusTotal submission it seems like the x86 build is getting flagged.
I submitted it to Microsoft for analysis on hopefully the right page.
Getting that unflagged will probably unflag the installer too.

**Comment by namazso** [comment]
Received a reply (wow, that was quick):
![image](https://user-images.githubusercontent.com/8676443/74109162-55c41680-4b81-11ea-96aa-b89e97a6e5e8.png)

**Comment by namazso** [comment]
Seems like the installer is still getting flagged despite the installed files all scanning clean. I submitted yet another analysis thing to Microsoft

**Comment by namazso** [comment]
Okay, got the same reply for the installer too, please do the definition update they mention an try using it now.

**Comment by JohnLGalt** [comment]
I ran the commands as shown in your ss.  The first one failed, with an error code, but I went ahead and ran the signature update.

I just downloaded a fresh copy of OHT and ran and it installed with no issues.  Closing ticket.
