### ISSUE TITLE
Freezes Windows Explorer when operating on folder symbolic link

### ISSUE THREAD

**Issue by blackwind** [namazso/OpenHashTab#21]
OpenHashTab reliably freezes Windows Explorer for me when operating on a folder symbolic link.

To reproduce:

1.) Create a symbolic link to a folder
2.) Open properties on the symbolic link
3.) Navigate to Hashes tab

Windows Explorer will freeze indefinitely until restarted.

**Comment by namazso** [comment]
This was fixed at some point, not sure when. Even recursive symlinks work now
