### ISSUE TITLE
Long path limitation

### ISSUE THREAD

**Issue by JustMyGithub** [namazso/OpenHashTab#22]
I created a testset to comare HashCheck and OpenHashTab.

in the Desktop Folder I created:

%L%.folder
 | - %S%.txt
 | - %L%.txt
 | - %L%.folder
      |-%L%.txt
      |-%L%2.txt

%L% is a very long string, %S% is a short string

HashCheck does result in "1 of 2 files hashed" (https://github.com/gurnec/HashCheck/issues/70)

OpenHashTab outputs 0/0/2/1 (1 seems to be the number of errors) and an errors description in the "hash" column.

which is much better, but:

- OpenHashTab cannot access %L%.folder\%L%.folder as well
- the pathnames shown are cut off
- The only part that is highlighted in red is in the "hash" field of %L%.folder\%L%.folder

suggestions:
1. Write filenames/subpath in an own line. This reduces the redundancy in the GUI (if more than one algorithm is selected) and allow users to spot error descriptions more easily.
2. highlight the 4th number in your statistics red, at least if it is > 0 - or even provide a label saying "there have been errors"

(Oh, and HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathsEnabled is set to 1 already)

**Comment by namazso** [comment]
Interesting, I tried to allow long filenames everywhere. I'll check if I receive good strings from explorer in the first place

**Comment by namazso** [comment]
Should be better now, the rest is explorer's limitation I think.

**Comment by JustMyGithub** [comment]
Would you please describe what you did change and which limitation is left? Thank you.

**Comment by namazso** [comment]
https://github.com/namazso/OpenHashTab/commit/f86b6b4917433ea2cebc22a316605f01ae244989

before this PathIsDirectory wasn't called with long-compatible paths so directories with overlong paths wouldn't work. Now they do. I also added manifest for long path support which I'm not sure if changes anything. What's left is that explorer seems to give us DOS shortpaths initially for whatever reason, which may result in this: 

![image](https://user-images.githubusercontent.com/8676443/96075942-7e3ca700-0eac-11eb-8543-dcf03b8a8ebd.png)
