### ISSUE TITLE
Indicate hash match more clearly

### ISSUE THREAD

**Issue by StrangePeanut** [namazso/OpenHashTab#23]
I still find myself double-checking a hash match often. Coloured text or even an ‘OK!’ would help a ton here.

**Comment by Darthagnon** [comment]
This is the GUI used by [HashCheck](https://github.com/gurnec/HashCheck) for checking hashes ![explorer_wLJ7KrCVI5](https://user-images.githubusercontent.com/20792748/106285907-f1d8a900-623c-11eb-9fc3-6e77330270be.png)

I find it works very well for me.

The old classic QuickSFV has a very similar GUI, that also works very well:
![QuickSFV_k7d279aUX3](https://user-images.githubusercontent.com/20792748/106286185-45e38d80-623d-11eb-86f5-7346533a964c.png)

**Comment by tERyceNzAchE** [comment]
HashCheck style Green/Red only please!

**Comment by tERyceNzAchE** [comment]
Please include a # Passed / # Failed as well.
When comparing many files you can easily miss one failed file in the list.

**Comment by namazso** [comment]
@tERyceNzAchE it's already there:

![image](https://user-images.githubusercontent.com/8676443/106395628-94428900-6403-11eb-9a62-f5fafbf06285.png)

format is (match/mismatch/unknown/unreadable)

**Comment by tERyceNzAchE** [comment]
> format is (match/mismatch/unknown/unreadable)

It would be much more clear to the user if it was explicit.
Match: 10, Mismatch: 0, Unknown: 1, Unreadable: 0

**Comment by Darthagnon** [comment]
[RapidCRC](https://ov2.eu/programs/rapidcrc-unicode) is another open-source hashing utility that has a GUI something like HashCheck.

There are screenshots on the website; here's the [GitHub](https://github.com/OV2/RapidCRC-Unicode)

**Comment by rbnmndz** [comment]
And  when "checking against:" finds a match, it would be more clear if a ✔️ or "match" was added to the result below, next to the algorithm or file name.

**Comment by megosugit** [comment]
Same here, I just tried this extension today.
When looking at a single file properties for instance, I was expecting the matching line to be highlighted in green (at least selected if color is not possible).

It would be much quicker and easier than reading the text under "check against" to see which one is a match.

I also don't understand the 0/0/1/0 format. I read the explanation but I don't think it applies when there is no .algo file present.

**Comment by namazso** [comment]
Fixed in https://github.com/namazso/OpenHashTab/commit/a01640de05ffe71588ebacaa1226c2b7a4165d05
