### ISSUE TITLE
Add support to BLAKE3 hashes.

### ISSUE THREAD

**Issue by ZarusMods** [namazso/OpenHashTab#25]
Hello, can you add BLAKE3 hashes in this program? I REALLY like this program.

**Comment by namazso** [comment]
I just added it, should be in next release which i plan to try and put together this week

**Comment by ZarusMods** [comment]
Ok,thanks

**Comment by Remonli** [comment]
> 
> 
> I just added it, should be in next release which i plan to try and put together this week

Is there any plan for new binary release ?

**Comment by whalehub** [comment]
@namazso Any news on the next release?

**Comment by namazso** [comment]
Whoop, turned out to be slightly more than a week. Wanted to fix long & network paths but forgot. Anyways, release is out.
