### ISSUE TITLE
Context menu for copy operations

### ISSUE THREAD

**Issue by circcc** [namazso/OpenHashTab#27]
1.Double-clicking, Right-clicking is not the standard way to copy.
Context menu("copy hash", "copy the line", "copy all") will be better.

~~2.Lowercase hash is better for reading.~~

**Comment by namazso** [comment]
1. I'll consider. It's meant to be rather fast to use, plus I didn't have to figure out context menus this way.
2. Will probably be a setting. I find uppercase more pleasing to the eyes.

**Comment by namazso** [comment]
option for hash casing for display and export has been added.

**Comment by namazso** [comment]
Added popup menu, available in latest dev build and in next release
