### ISSUE TITLE
VirusTotal False Positives

### ISSUE THREAD

**Issue by brian6932** [namazso/OpenHashTab#28]
![image](https://user-images.githubusercontent.com/18603393/96354070-41390600-10a0-11eb-9088-6849ddb83618.png)

https://www.virustotal.com/gui/file/1ea29379f25647f98470a1301e81fa4895333df6bd13c4cfd6fc6c30292cac7c/detection

**Comment by namazso** [comment]
I don't really care about third party malware known as antiviruses. If it's Defender I'll take steps, otherwise this is not an issue. If you care about them, submit as false positive.
