### ISSUE TITLE
Sumfile default filenames

### ISSUE THREAD

**Issue by mariomadproductions** [namazso/OpenHashTab#30]
If I checksum a single file, then click "export", the suggested sumfile filename is the same as the checksummed file. I think it would be better if something was appended to it. It could be customisable.

If I checksum multiple files, then click "export", the suggested sumfile filename is blank. Again, I think it would be better if there was an appropriate name there by default.

**Comment by namazso** [comment]
This is already the behavior for ones that have known sumfile extensions (listed here https://github.com/namazso/OpenHashTab/blob/master/OpenHashTab/Hasher.cpp#L275-L284 ).

What do you suggest for the rest?

**Comment by mariomadproductions** [comment]
Ah. For CRC32, it could be "[sfv](https://en.wikipedia.org/wiki/Simple_file_verification)". For the others, it could just be the name of the hash, even if that's not a common file extension. For multiple hashes, it could just be "hashes".

Currently, if multiple files are selected, it just has the extension ".md5" suggested, without any "root". Maybe the root could again be "hashes", or maybe it should be named after the parent folder.

**Comment by namazso** [comment]
> Ah. For CRC32, it could be "sfv".

sfvs aren't in sumfile format and thus unsupported as of now, both for export and "import" (checking). I'd prefer not to name it confusingly.

>  For the others, it could just be the name of the hash, even if that's not a common file extension.

hm.. I'll think about that. I don't like how .sha3 is sha3-512, but the rest would have .sha3-256 and the like.

> Currently, if multiple files are selected, it just has the extension ".md5" suggested, without any "root". Maybe the root could again be "hashes" (e.g. "hashes.md5"), or maybe it should be named after the parent folder.

The parent folder thing is a good idea, although might not be trivial to implement. Windows (aka DOS) paths are very confusing things to deal with.

**Comment by Darthagnon** [comment]
[HashCheck](https://github.com/gurnec/HashCheck/releases/) (2016) lists file extensions as follows:
```
CRC32 (*.sfv)
MD5 (*.md5)
SHA-1 (*.sha1)
SHA-256 (*.sha256)
SHA-512 (*.sha512)
SHA3-256 (*.sha3-256)
SHA3-512 (*.sha3-512)
```

[checksum](https://corz.org/windows/software/checksum/) (2015) attempted to introduce a further standard for mixed hashes (i.e. all selected hashes: CRC32, MD5, etc. all in one file):
```
Mixed hashes (*.hash)
```
I rambled further about this in #32, which has a lot of crossover with this issue.

**Comment by namazso** [comment]
added a default filename base of `checksums` and a default extensions `.sums` for algorithms that don't have known export names. so now trying to export md2 will offer filename like `checksums.sums`.
