### ISSUE TITLE
Malicious Behavior Detected

### ISSUE THREAD

**Issue by SSLbits** [namazso/OpenHashTab#33]
Multiple AV engines detect malicious activity caused by the installer:
https://www.virustotal.com/gui/file/1ea29379f25647f98470a1301e81fa4895333df6bd13c4cfd6fc6c30292cac7c/detection

https://www.hybrid-analysis.com/sample/1ea29379f25647f98470a1301e81fa4895333df6bd13c4cfd6fc6c30292cac7c/5f8b662e7290cf29295735cb

The network activity is particularly worrisome. It tries to contact 52.255.148.73 over port 443. The AV analysis also detects increased number of ARP broadcast requests (network device lookup): 
Attempt to find devices in networks: "192.168.240.2/32, 192.168.241.219/32, 192.168.242.99/32, 192.168.242.137/32, ..."

**Comment by namazso** [comment]
there are no network requests made, their behavioral engine just sucks. if you clicked the OSINT button, you'd see that it's microsoft telemetry servers:
![image](https://user-images.githubusercontent.com/8676443/98802202-365d6100-2413-11eb-9bf7-771d74907a3a.png)

unless you think i installed malware C&C server on microsoft's telemetry servers, i'm going to ignore this.
compile it yourself if worried

**Comment by namazso** [comment]
also i dont care about detections by those scam hash calculators either. submit as fp if you do.

**Comment by namazso** [comment]
As a little update related to this, development builds and future releases are now:
- reproducible
- ship with pdbs
- aren't built on my machine, but on GitHub Actions

Development build artifacts are available here: https://github.com/namazso/OpenHashTab/actions

So now you can grab the source code and build identical binaries if you feel like it.

**Comment by SSLbits** [comment]
thanks. I'm trying to work with the AV engine detectors to whitelist the app. Security at my job won't let me run it with these detections :\
