### ISSUE TITLE
Monitor hash from clipboard

### ISSUE THREAD

**Issue by Riajyuu** [namazso/OpenHashTab#4]
This is a feature of HashTab.
If any hash string is detected is Windows clipboard, HasbTab will take it autoly and check against it when user click the corresponding tab.

**Comment by Remonli** [comment]
Is it possible to add a icon to show the result like hashtab? If it matches, there will be a green check mark , if it doesn't match, then red cross mark.

**Comment by namazso** [comment]
@Remonli I'd prefer not to include any icons, so I'll have to figure out if there is a way to grab stock windows icons for this.
Another problem is that the GUI is crowded, there is literally no space for an icon.

**Comment by Remonli** [comment]
@namazso Then how about highlight the result by changing color ? "No match found" could be changed in red when doesn't match , in case of it matches,"algorithm/file name" could be changed 
to "algorithm matched" and green color, file name is not necessary as it already shows on the top 
of properties page.
