### ISSUE TITLE
Support more algorithms

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [namazso/OpenHashTab#45]
Integrate one of them would be allowed to use more hashing algorithms:
* [XKCP](https://github.com/XKCP/XKCP)
* [xxHash](https://github.com/Cyan4973/xxHash)

**Comment by namazso** [comment]
The XKCP build system is rather confusing, so we'll see about that. I wish there was an optimized assembly version that's not written for Linux / SysV ABI. For some reason this is a pattern I see occurring with all the crypto implementations. Considering I use clang for compilation, I could easily use anything that has inline assembly in gcc-style, and that would avoid all the ABI problems. Anyways, it looks like a good candidate for mitigating the current awful performance of the SHA3 family too.

xxHash looks rather simple to implement

**Comment by namazso** [comment]
Just added XKCP. From the algorithms that have customizable output I set their defaults from KeccakSum:
- KangarooTwelve - 264 bits
- ParallelHash128 - 264 bits
- ParallelHash256 - 528 bits
size customization isn't possible at the moment, and not sure if i ever want to support it. It's not practical
