### ISSUE TITLE
About the Option of "Add date"

### ISSUE THREAD

**Issue by nkh0472** [namazso/OpenHashTab#49]
I noticed that the following two options are subordinate, which are `Add banner to exported files` and `Add date to banner`. It means when disabled the first option, whether the second one is enabled or not, it doesn‘t work. 

Normally, the options like the latter should turn gray and unclickable or make it indented to remind users.  Considering that the newly added clipboard related options use the indent, I think this should also be consistent.

Or, maybe it's better to make the option like `Add date to exported files`.

**Comment by nkh0472** [comment]
And when using `Look for sumfiles next to files being hashed`, the results are shown in brown and red. I was very confused when I first used it. I think it would be better to add text hints.
After all, colors represent different meanings in different cultures, and text cues are more friendly to color blind patients.

**Comment by namazso** [comment]
Just added everything from your first comment:

![image](https://user-images.githubusercontent.com/8676443/101982113-01db0000-3c72-11eb-9bdd-80fa7dbf6f0e.png)

As for the color encoding, I plan (for quite a long time now) to replace the main hash listview with a treelistview, where textual representation of match type will be present too. This is actually why I haven't really worked on any other UI issues related to the main listview either - no point when I plan to trash it eventually.

**Comment by nkh0472** [comment]
That is fantastic!
The bunch of practical features adding to the project recently making this project getting better and better. And it's surpassing a lot of similar software!
