### ISSUE TITLE
Add "All" as an export option

### ISSUE THREAD

**Issue by Riajyuu** [namazso/OpenHashTab#5]
This means I want all of the raw data :-)

**Comment by namazso** [comment]
I'm unsure of what you mean by this.
Do you mean the whole contents in the right-click style format?
The other export / copy options are specifically for sumfiles (format produced by *sum programs) which don't contain the algorithm.

**Comment by Riajyuu** [comment]
Sorry. I seem misunderstanding the feature a bit.

**Comment by namazso** [comment]
Still, I added a way to copy everything in rightclick style, by double right clicking.
