### ISSUE TITLE
Feature Request - option to stop auto-calculating hashes

### ISSUE THREAD

**Issue by ericswpark** [namazso/OpenHashTab#52]
Hello! Would it be possible to add an option to stop auto-calculating hashes? When comparing large files I don't want to calculate all hashes because it would take a long time. Instead, I think it would be better if hashes were calculated on click, so I can just click on a particular hashing algorithm and OHT would calculate it for me without computing the other algorithms.

Perhaps this behavior can be tied to a settings checkbox, "Automatically calculate hashes when tab is opened" so that people who like the current behavior can continue using OHT as-is? Thanks!

**Comment by namazso** [comment]
why is the current cancel button not enough?

**Comment by namazso** [comment]
oh, upon rereading i see that you want to individually calculate per-algorithm. In case of a single file when doing not more algorithms than CPU threads you have, the bottleneck is the slowest selected algorithm. whether the other ones are calculated or not ultimately doesn't matter much, unless for energy usage or wanting to use the remaining computing power to do something in the meantime (both of which are quite niche).

**Comment by ericswpark** [comment]
> why is the current cancel button not enough? starting reading the files then throwing away the result when cancelled is only possibly better than not starting it.

You mean the cancel button added in FR #31? Because the last release right now doesn't have a cancel button yet.

> oh, upon rereading i see that you want to individually calculate per-algorithm. In case of a single file when doing not more algorithms than CPU threads you have, the bottleneck is the slowest selected algorithm. whether the other ones are calculated or not ultimately doesn't matter much, unless for energy usage or wanting to use the remaining computing power to do something in the meantime (both of which are quite niche).

Oh, I didn't know that, thanks! Closing as this appears to be a non-issue.

**Comment by namazso** [comment]
> Because the last release right now doesn't have a cancel button yet.

yeah, try a dev build
