### ISSUE TITLE
Feature Request: When verifying a hash file, only calculate the algorithm in the file. 

### ISSUE THREAD

**Issue by tERyceNzAchE** [namazso/OpenHashTab#55]
When verifying a hash file, to increase performance only calculate and show the algorithms used in the hash file.

**Comment by namazso** [comment]
This is possible already in 3.0.1 (pre-release currently) but not really communicated well. Simply unselect all algorithms. The correct one (if detected from extension) is always automatically enabled. I'll think of making this explicitly an option

**Comment by tERyceNzAchE** [comment]
Perhaps I wasn't clear.  User should not have to unselect all algorithms, OpenHashTab should do that automatically if it is in verify mode.

Having multiple algorithms enabled when not in verify mode is very useful.

**Comment by namazso** [comment]
I see. I'll probably add this as an option soon. Also, just a sidenote: it isn't too bad performance-wise to calculate all of them - usually the bottleneck is (if not the disk) the slowest algorithm. So if you calculate some SHA-2 hash, you get SHA-1 and MD5 for practically free.

**Comment by tERyceNzAchE** [comment]
Thanks.

I'm using 3.0.1 now and it can be pretty bad when I'm verifying a large directory (10+ GB) and have several algorithms enabled.  Not horrible, but very noticeable.
