### ISSUE TITLE
Date error?

### ISSUE THREAD

**Issue by wvxwxvw** [namazso/OpenHashTab#57]
Processed file  
![2021 02 02_225111](https://user-images.githubusercontent.com/13194155/106655338-45832380-65aa-11eb-91ae-ed84248458bc.png)  
  
System time  
![2021 02 02_225232](https://user-images.githubusercontent.com/13194155/106655375-503db880-65aa-11eb-8f54-b3e259f32d3a.png) 
  
What does this date mean in the exported file?  
![2021 02 02_225139](https://user-images.githubusercontent.com/13194155/106655393-5764c680-65aa-11eb-879e-f504cddef571.png)  
  
Win 7 x64, there are no antiviruses and proactives.

**Comment by namazso** [comment]
It is merely to comply with the corz .hash format. Since there is no public documentation to the format, and it is not a standard (ISO8601) timestamp, I filled it up with a known valid date.
I really don't want to reverse corz checksum to find out what kind of timestamp format he uses

**Comment by namazso** [comment]
actually i just ended up checking it out really fast. unfortunately but not unsurprisingly it's garbage.

https://user-images.githubusercontent.com/8676443/106657778-b9b6ca80-659c-11eb-88b9-f737dfa550ff.mp4

**Comment by wvxwxvw** [comment]
I'm happy for Win 10, but I have Win 7. I wrote about this in the first post.
	
Although, of course, you can ignore Win 7, because according to all the paid statistics, very few people are sitting on it. But the reality is different from these statistics.

**Comment by namazso** [comment]
i.. uh.. what? I don't see the relevance of this to what I just explained.

corz checksum's date features are fundamentally broken and should never be used in a security-aware product. this applies to every windows version.

**Comment by wvxwxvw** [comment]
Sorry. I didn't get it right away.

**Comment by g0blin-NN** [comment]
@namazso 
is this not true?
`;     73709175  18:34.24 2021-05-25 (UTC+3) FW_RT_AX56U_300438642808.rar
4f546d20401f25db75de3216879c3951f60a1f6ab1d8b8ed86383e040f7e5df5 *FW_RT_AX56U_300438642808.rar
`
imho, better a correct date than not understand what is by some standard. can just remove, still does not carry a semantic load?

**Comment by wvxwxvw** [comment]
@g0blin-NN 
I didn't understand what it was at all and just turned it off. ) I think it's just a redundant feature.

**Comment by namazso** [comment]
@g0blin-NN i'm not sure what you mean. this issue is about how there are intentionally incorrect dates written in the output files. this is because corz .hash is broken, and stores local time without timezone rather than some standardized format, then relies on this for updating hashes.

**Comment by g0blin-NN** [comment]
@wvxwxvw conceived like this...
>Report Changed/Corrupt/Missing States..
checksum can optionally store a file's modification date and time along with the checksums, like so..
>
>```
>#md5#info.nfo#2009.09.26@19.49:36
>5deee1f6ac75961d2f5b3cfc01bdb39c *info.nfo
>```
>Thanks to the extra information, during verification checksum will report files with mismatched hashes as either "CHANGED" (they have been modified by some user/process) or "CORRUPT", where the modification time stamp is unchanged.
>
>These will show as a different color in your HTML logs.
>
>You can choose whether or not to report (and log) missing, changed, or corrupted files. For example, if you only want to know about CORRUPT files, but don't care about changed or missing files, you would set..
>
>```
>report_missing=false
>report_changed=false
>report_corrupt=true
>```
>As one commenter (below) pointed out, with this sort of functionality, checksum would become "the only tool against silent data corruption". I believe this goal has now been achieved.
>
>The chosen algorithm is also stored along with this information, for possible future use (aye, more algorithms!).
 
@namazso the question remains open. why is it in this program if it doesn't work?

**Comment by namazso** [comment]
@g0blin-NN what do you not understand? the implementation of corz .hash is **_broken_** because it mishandles timezones. i cannot fix someone else's program, so the next best thing is simply fill it up with a bogus date that causes the least problems. what else would you want me to do, remove support for the format entirely?  I don't see how that would benefit the user. or try to implement same-kind-of-broken behavior? I'd rather not intentionally put bugs into my code either.

**Comment by g0blin-NN** [comment]
@namazso Yes. kill completely corz.hash. still doesn't work. instead, think about a working option.
it creates
`; 73709175 18:34.24 2021-05-25 (UTC+3) FW_RT_AX56U_300438642808.rar 4f546d20401f25db75de3216879c3951f60a1f6ab1d8b8ed86383e040f7e5df5 *FW_RT_AX56U_300438642808.rar`
[RapidCRC](https://github.com/OV2/RapidCRC-Unicode)
but for information only. but you can go further, right?
