### ISSUE TITLE
Automatic or one-click export of hash file

### ISSUE THREAD

**Issue by Stimmenhotel** [namazso/OpenHashTab#59]
Since you are offering many options about exporting and using already created hash files ... It would be nice to choose an option of automatically export the file.

Or, maybe even better, to export the predefined files using only one click instead of a save to window.

An option could be something like Ctrl+click to save them in the same folder or ask for location.

**Comment by namazso** [comment]
oh yea forgot to comment it here, this is now available in dev builds, the way to do it is Shift+click on export.
