### ISSUE TITLE
I don't know which version to choose.

### ISSUE THREAD

**Issue by Dhyfer1** [namazso/OpenHashTab#60]
Hi.

I am a HashTab user and I recently discovered OpenHashTab and I would like to try it, but when I go to the releases section I see that the latest version has two executable files (OpenHashTab_setup_user.exe and OpenHashTab_setup_system.exe).

What is the difference between the two? Which one should I choose? 

That's all. Thanks in advance.

**Comment by namazso** [comment]
User installs for current user only, system installs for every user. If you're the sole user of your computer it absolutely doesn't matter.

**Comment by Dhyfer1** [comment]
Hi @namazso 

Ok, now I understand. Thank you very much for your attention to my problem, I will close it now. Thanks. 👍
