### ISSUE TITLE
Error when opening a "checksums.*" file.

### ISSUE THREAD

**Issue by LuxLOL** [namazso/OpenHashTab#61]
Hi,

When i try top open a "checksums.*" file i get this error below.
```
RunDLL
Error in C:\Users\Admin\AppData\Local\Programs\OpenHashTab\OpenHashTab.dll
Missing entry: StandaloneEntry
```

**Comment by namazso** [comment]
is the file it complains about actually there?

**Comment by LuxLOL** [comment]
Yes the file is there.
I also tested it on a fresh installed Up-to-Date Windows 10.

**Comment by namazso** [comment]
Weird, i'm not able to reproduce it on my VMs.
You seem to have used the user installer. did you run it as the user you're using, and without "Run as Administrator"?

**Comment by LuxLOL** [comment]
After checking again i noticed that this error only happens on a 32-bit Operating System.
