### ISSUE TITLE
File "checksums.*" Error "cannot find the file"

### ISSUE THREAD

**Issue by LuxLOL** [namazso/OpenHashTab#62]
Hi
If i hash a file on the Desktop and then Export it, and when i then click on the "checksums.*" file then i get this error below:
`Error	The system cannot find the file specified`

**Comment by namazso** [comment]
is this also only happening on 32 bit Windows?

**Comment by LuxLOL** [comment]
I couldn't test it on the 32-bit because the "checksums.*" file won't open on the 32-bit.

**Comment by namazso** [comment]
I see. are you exporting the checksum file next to the files being hashed? It isn't intended to work any other way, since relativizing paths would be way too troublesome

**Comment by LuxLOL** [comment]
Exactly. I have exported the checksum file next to the files being hashed.
It works with the outdated [HashCheck](https://github.com/gurnec/HashCheck) tool. I think this tool simple leaves out the full path.

**Comment by namazso** [comment]
i see. can you post a zip of the file and the exported checksum file, while keeping the hierarchy (if any)?

**Comment by LuxLOL** [comment]
This issues can be closed. It was a mistake on my side.
The hash file was saved at "C:\Users\Public\Desktop"
And the checksum file was saved at "C:\Users\Admin\Desktop"
