### ISSUE TITLE
registering shell context

### ISSUE THREAD

**Issue by orbittwz** [namazso/OpenHashTab#64]
Hey, first this is great, finally a replacer to HashCheck that work and looks amazing!
Thank you very much for that.
One thing that happened with my installation, is after I installed the program, when I double click a SFV file, it says the file is not recognizable by Windows...
I need to right click and select Hashes option from the shell menu...
Is there a way to register the program to default do this instead of manually performing the selection?
I thought in the installation, I chose to install shell extension, and the program will default all hash files to it automatically...
let me know...

**Comment by orbittwz** [comment]
to add to this... I found out that doing export to SFV file (maybe it's other formats) of files hashes, it's not sorted according to file name... something to check maybe on your end?

**Comment by orbittwz** [comment]
another issue, why the program also checks the SFV file itself instead of just what inside it? I didn't want to check the file itself...
any option to disable it?

**Comment by namazso** [comment]
>  when I double click a SFV file, it says the file is not recognizable by Windows...

whoops, i forgot to add that extension. originally only export was supported for sfv. Just fixed this in ce0d4ab63b3e8f41a29061b593433d03777d3930

For now you can associate it manually via registry, or just using a development build with the fix

> I found out that doing export to SFV file of files hashes, it's not sorted according to file name... something to check maybe on your end?

The wikipedia article on [SFV](https://en.wikipedia.org/wiki/Simple_file_verification) mentions no sorting. cksfv does not sort either:

![image](https://user-images.githubusercontent.com/8676443/108068677-af97d000-7062-11eb-84b3-5853d84476e1.png)

>(maybe it's other formats)

 md5sum also does not sort:

![image](https://user-images.githubusercontent.com/8676443/108068331-39936900-7062-11eb-9341-2eadc85941c7.png)

> another issue, why the program also checks the SFV file itself instead of just what inside it? I didn't want to check the file itself... any option to disable it?

not yet, but it's planned soon :tm:
didn't want to add too much translation-requiring strings close to release

**Comment by orbittwz** [comment]
This is great thanks!
Since I don't know how to build the current depo, how can I associate it using registry?
Yeah, HashCheck also didn't sort the SFV after creation, it's really weird...
And OK I can wait for the file itself check omitting :)

**Comment by namazso** [comment]
oh you don't need to build, dev builds are built automatically on push: https://github.com/namazso/OpenHashTab/actions?query=branch%3Amaster

**Comment by orbittwz** [comment]
very cool! didn't knew github can do this on the go...
OK I can close this for now!
looking forward to the next update :)
