### ISSUE TITLE
Support KangarooTwelve 256/512

### ISSUE THREAD

**Issue by tERyceNzAchE** [namazso/OpenHashTab#65]
These are more commonly used (k12sum) than the 264 that is currently supported.

**Comment by namazso** [comment]
interesting choice in k12sum, considering keccaksum defaults to 264

**Comment by tERyceNzAchE** [comment]
264 seems like an odd default (33 bytes).

k12sum defaults to 32 bytes/256 bits but the length can be specified by the user.
