### ISSUE TITLE
Feature Request: Add GOST Support

### ISSUE THREAD

**Issue by NastyaGrifon** [namazso/OpenHashTab#67]
The standard for GOST hash function was originally developed for use in USSR, nowadays it is commonly used in Russia and former USSR countries. It is required for military (e.g Linux Astra) and state use cases.

There are two implementations of the GOST hash:

- GOST R 34.11-94 (Developed in 1994. The legacy one, so to speak. Retired in 2013)
- GOST R 34.11-12 (Developed in 2012. The widely used one)

Both support 256 and 512 bit digest. I've found two FOSS implementations of the latter: [Link 1](https://github.com/adegtyarev/streebog) [Link 2](https://github.com/okazymyrov/stribog)

Is it possible to integrate either of them in OpenHashTab?

**Comment by NastyaGrifon** [comment]
There is apparently 'gostsum' available in [debian](https://packages.debian.org/sid/gostsum) and [ubuntu](https://packages.ubuntu.com/en/hirsute/gostsum) repos, which use the newest GOST R 34.12-2015. Since it is not widely used  yet, there is no need in integrating it just yet

**Comment by namazso** [comment]
added the streebog implementation, should be available in latest dev build and next release
