### ISSUE TITLE
Improved Simplified Chinese translation.

### ISSUE THREAD

**Issue by NieLnchn** [namazso/OpenHashTab#7]
First of all, I would like to thank the developers for developing this software and fixing the problem in time.
I saw that the Simplified Chinese translation in the software is very bad, so I optimized the translation, but I do n’t know how to submit it, so I sent it here, please forgive me.

[Simplified Chinese.txt](https://github.com/namazso/OpenHashTab/files/4352349/Simplified.Chinese.txt)

**Comment by namazso** [comment]
i'm the sole developer and thanks.
and you did correctly by posting it as an issue, pull requests are mainly for people already familiar with developing software on github.
