### ISSUE TITLE
Code clarification on dialog box styles

### ISSUE THREAD

**Issue by GiovanniDicanio** [namazso/OpenHashTab#71]
Just a clarification for something you wrote in your code:

https://github.com/namazso/OpenHashTab/blob/364fb3296a80e76a2d69a5b7c9936bdaf8f65bae/OpenHashTab/wnd.h#L346

In `<WinUser.h>`:

```
#define DS_SETFONT          0x40L   /* User specified font for Dlg controls */

#define DS_FIXEDSYS         0x0008L

#define DS_SHELLFONT        (DS_SETFONT | DS_FIXEDSYS)

```

**Comment by namazso** [comment]
thanks, i was only looking window styles at the time when tried to figure out what are the differences between child windows and normal windows
