### ISSUE TITLE
Check potential failures of UTF-8/UTF-16 conversions

### ISSUE THREAD

**Issue by GiovanniDicanio** [namazso/OpenHashTab#72]
https://github.com/namazso/OpenHashTab/blob/99077eb611f251915ac23447beb96cd1a51d8903/OpenHashTab/utl.cpp#L280

I would suggest to check for potential failures in calls to `MultiByteToWideChar` when converting from UTF-8 to UTF-16, and in the opposite conversion direction, too.

For example, if you are reading from an external file that is supposed to be encoded in UTF-8 and an invalid sequence is found, it's better to stop processing that file and show an error message box.

**Comment by namazso** [comment]
the only instance where untrusted input is handled with that function is when parsing filenames from sumfiles. I added an extra check to fail the entire file when invalid encoding is found
