### ISSUE TITLE
Some french translation doesn't fit

### ISSUE THREAD

**Issue by Nico207** [namazso/OpenHashTab#74]
![image](https://user-images.githubusercontent.com/1179972/113149511-62974400-9233-11eb-9f81-b984a757e4a1.png)

I can suggest the following:
"CLIPBOARD": "Copier"
"SUMFILE_USE_DOUBLE_SPACE": "Séparateur \<espace>\<espace> à la place de \<espace><*>"

Or make tabs to separate parameters.

Many thanks for your great tool ! 👏

**Comment by Albirew** [comment]
Agreed:
- there's no need to specify "dans le presse-papier" (to clipboard) when an export button is right after.
- having a carriage return to prevent unreadable content would be good.

**Comment by namazso** [comment]
should have the new translations in latest development builds already

**Comment by namazso** [comment]
my bad, \*now\* the latest dev build (downloadable from actions) have the new translations. Forgot that Weblate committing is delayed by 24 hours

**Comment by namazso** [comment]
Should be fixed for now in the updated Settings UI of the current development build:

![image](https://user-images.githubusercontent.com/8676443/164141851-b82e4290-3f74-4957-80be-0c1b9c55777d.png)
