### ISSUE TITLE
Define in readme differences between user and system setup (if there is one)

### ISSUE THREAD

**Issue by Nico207** [namazso/OpenHashTab#77]
Hi,

I'm not sure which one to choose...
Apart the installation for one user or all users, what are the differences between the `user` and the `system` setups?

If this is the only difference, why not make only one setup with choice to install for current user or for all users ?

**Comment by namazso** [comment]
> Apart the installation for one user or all users, what are the differences between the user and the system setups?
Nothing.

> If this is the only difference, why not make only one setup with choice to install for current user or for all users ?
Because i didn't know of the `PrivilegesRequiredOverridesAllowed` option of InnoSetup until 5 minutes ago. I guess the next version will be built with that instead.
