### ISSUE TITLE
Hash function CRC-64

### ISSUE THREAD

**Issue by qcyblm** [namazso/OpenHashTab#85]
Please add support for CRC-64 output. Thanks

**Comment by namazso** [comment]
do you know of any performant implementations? preferably one with the CRC instructions. 7-Zip supports them in beta, but source code isn't released for betas unfortunately.

**Comment by qcyblm** [comment]
The source code for 7-Zip beta has been released：https://www.7-zip.org/a/7z2103-src.7z.
 [mrhooray /crc-rs](https://github.com/mrhooray/crc-rs) Rust implementation of CRC(8, 16, 32, 64). MSRV is 1.46.

**Comment by namazso** [comment]
ended up with a custom implementation that benches 1329 MB/s on my i7-7700HQ
