### ISSUE TITLE
Large file with .md5 extension isn't recognized as containing hashes

### ISSUE THREAD

**Issue by Anton-V-K** [namazso/OpenHashTab#97]
When double-clicking a file with .md5 extension , the app opens it and generates hashes for it (which is quite useless).
How to make the app verify the checksums instead?
I think, this should be a default action for files with extensions .md5/.sha1/etc.
The file was generated with ExactFile and has the content like:
```
; Checksums generated by ExactFile 1.0.0.15
; http://www.exactfile.com
; 29.11.2021 0:56:25

6ddac8c5ce38b6d929948a5e951cf234 *window_PNG17693.png
c8ddc6d5d28488fd91d8116a985047ff *Всемирный день ребёнка.docx
...
```

**Comment by Anton-V-K** [comment]
Thanks for quick response.
Here is the full file [checksums.md5.zip](https://github.com/namazso/OpenHashTab/files/7620554/checksums.md5.zip)

**Comment by namazso** [comment]
Ah, it's the size, currently files over 1 MB are not checked for sumfile-ness as checking is rather expensive and happens early on. I guess i should make this into some sort of configurable option. Or just try to parse anything regardless of size and early-fail if something cannot be a valid sumfile, then only edge cases should cause performance problems like a file full of newlines or something.

**Comment by namazso** [comment]
Should be fixed in [latest development build](https://nightly.link/namazso/OpenHashTab/workflows/ci/master/setup.zip)
