### ISSUE TITLE
Uninstall?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [namazso/OpenHashTab#99]
How do I uninstall it? There's no entry in Add Remove Programs.? Also, an option in settings to enable/disable the context-menu entry would be helpful.

**Comment by namazso** [comment]
If you installed it system-wide there should be an entry in Add or Remove Programs. For an user install there shpuld be an uninstaller shortcut in Start Menu. If not, browse to %localappdata%\Programs\OpenHashTab and run the uninstaller from there

**Comment by YouveGotMeowxy** [comment]
Thank you :)
